
spring:
  datasource:
    url: jdbc:h2:mem:giljabi
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
# H2 Settings
h2:
  console:
  enabled: true
  path: /h2-console
#  org.hibernate.type: trace
